### PR TITLE
Add earlgrey script

### PR DESCRIPTION
**Pull request by wwest4**

### CODE REVIEW

**Comment by filler** [comment]
:bomb: :boom: 

You gotta load these up in `hubot-scripts.json` also, no?

**Comment by filler** [comment]
dat rebase tho.

**Comment by wwest4** [comment]
👍

**Comment by filler** [comment]
A+++ WOULD REVIEW AGAIN

:+1: lgtm

**Comment by filler** [comment]
I dont like merging other peoples PRs.  Feel free to merge and Ill push to heroku.

**Pull request merged**
